import Head from "next/head";
import Link from "next/link";
import PDFUploader from "~/components/PDFUploader";
import TransactionList from "~/components/transactions";

export default function Home() {
  return (
    <>
      <Head>
        <title>Budget Project</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Budget <span className="text-[hsl(280,100%,70%)]">Project</span>
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <a
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Socials →</h3>
              <div className="text-lg">
                If you want to know more about the project, check out the socials
              </div>
            </a>
            <a
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Github Links →</h3>
              <div className="text-lg">
                Learn more about the repos that power this site
              </div>
            </a>
          </div>
          <TransactionList />
          <PDFUploader />
        </div>
      </main>
    </>
  );
}
